-- FACT TABLE: Transactions (Grain: Line item per basket)
CREATE TABLE fact_transactions (
    household_key INT NOT NULL,
    BASKET_ID BIGINT NOT NULL,
    DAY INT NOT NULL,
    DATE DATE NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    SALES_VALUE DECIMAL(10,2) NOT NULL,
    RETAIL_DISC DECIMAL(10,2) NOT NULL,
    COUPON_DISC DECIMAL(10,2) NOT NULL,
    COUPON_MATCH_DISC DECIMAL(10,2),
    TRANS_TIME TIME,
    STORE_ID INT,
    WEEK_NO INT,
    TOTAL_DISCOUNT_ABS DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (BASKET_ID, PRODUCT_ID, DAY)
);

-- FACT TABLE: Redemptions (Grain: Coupon redemption event)
CREATE TABLE fact_redemptions (
    household_key INT NOT NULL,
    DAY INT NOT NULL,
    DATE DATE NOT NULL,
    COUPON_UPC BIGINT NOT NULL,
    CAMPAIGN INT NOT NULL,
    PRIMARY KEY (household_key, COUPON_UPC, DAY)
);

-- DIMENSION: Household
CREATE TABLE dim_household (
    household_key INT PRIMARY KEY,
    AGE_DESC VARCHAR(20) NOT NULL DEFAULT 'Unknown',
    MARITAL_STATUS_CODE VARCHAR(5) DEFAULT 'Unknown',
    INCOME_DESC VARCHAR(20) NOT NULL DEFAULT 'Unknown',
    HOMEOWNER_DESC VARCHAR(20) DEFAULT 'Unknown',
    HH_COMP_DESC VARCHAR(30) NOT NULL DEFAULT 'Unknown',
    HOUSEHOLD_SIZE_DESC VARCHAR(5) DEFAULT 'Unknown',
    KID_CATEGORY_DESC VARCHAR(20) DEFAULT 'Unknown'
);

-- DIMENSION: Product
CREATE TABLE dim_product (
    PRODUCT_ID INT PRIMARY KEY,
    MANUFACTURER INT,
    DEPARTMENT VARCHAR(50) NOT NULL,
    BRAND VARCHAR(50),
    COMMODITY_DESC VARCHAR(100) NOT NULL,
    SUB_COMMODITY_DESC VARCHAR(100)
);

-- DIMENSION: Campaign
CREATE TABLE dim_campaign (
    CAMPAIGN INT PRIMARY KEY,
    DESCRIPTION VARCHAR(10) NOT NULL,
    CAMPAIGN_TYPE_LABEL VARCHAR(20) NOT NULL,
    START_DAY INT NOT NULL,
    END_DAY INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    DURATION_DAYS INT NOT NULL
);

-- DIMENSION: Calendar
CREATE TABLE dim_calendar (
    Date DATE PRIMARY KEY,
    DAY INT NOT NULL,
    Day_of_Week INT NOT NULL,
    Day_Name VARCHAR(10) NOT NULL,
    Month INT NOT NULL,
    Month_Name VARCHAR(10) NOT NULL,
    Quarter INT NOT NULL,
    Year INT NOT NULL,
    Is_Weekend BOOLEAN NOT NULL
);